**

!pyproject.toml
!uv.lock
!src/
!src/**
!docker/
!docker/**
!assets/wallpaper_1280x1024.png

**/__pycache__/
**/*.pyc
**/*.pyo
**/.pytest_cache
**/.ruff_cache
**/.mypy_cache
**/.coverage
**/.env
**/.env.*
